const STORE_KEY = "musiai_mvp_v1";
const state = { user: null, tracks: [], mediaRecorder: null, chunks: [], voiceBlob: null };
function load(){try{const raw=localStorage.getItem(STORE_KEY);if(!raw)return;const data=JSON.parse(raw);state.user=data.user||null;state.tracks=data.tracks||[];}catch(_){}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify({user:state.user,tracks:state.tracks}));}
function uid(){return "id_"+Math.random().toString(36).slice(2,10)+Date.now().toString(36);}
function toast(msg){const el=document.getElementById("toast");el.textContent=msg;el.classList.remove("hidden");clearTimeout(toast._t);toast._t=setTimeout(()=>el.classList.add("hidden"),2800);}
function showView(name){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));const el=document.getElementById("view-"+name);if(el)el.classList.add("active");if(name==="artist"&&(!state.user||state.user.role!=="artist")){showView("auth");toast("Sign in as artist to open Studio");return;}if(name==="voice"&&!state.user){showView("auth");return;}refreshUI();}
function refreshUI(){const logged=!!state.user;document.getElementById("btn-login").classList.toggle("hidden",logged);document.getElementById("btn-start").classList.toggle("hidden",logged);document.getElementById("user-chip").classList.toggle("hidden",!logged);document.querySelectorAll(".artist-only").forEach(n=>{n.classList.toggle("hidden",!(state.user&&state.user.role==="artist"));});if(state.user)document.getElementById("user-name").textContent=state.user.name;const artists=new Set(state.tracks.map(t=>t.artistId)).size;const verified=state.tracks.filter(t=>t.matchStatus==="passed").length;let artistCount=artists;if(state.user&&state.user.role==="artist"&&state.user.voiceVerified){if(!state.tracks.some(t=>t.artistId===state.user.id))artistCount+=1;}document.getElementById("stat-artists").textContent=String(artistCount);document.getElementById("stat-tracks").textContent=String(verified);if(state.user&&state.user.role==="artist"){const mine=state.tracks.filter(t=>t.artistId===state.user.id);const streams=mine.reduce((s,t)=>s+(t.streams||0),0);const earn=mine.reduce((s,t)=>s+(t.earnings||0),0);document.getElementById("stream-total").textContent=String(streams);document.getElementById("earn-total").textContent="$"+earn.toFixed(2);const badge=document.getElementById("voice-badge");if(state.user.voiceVerified){badge.textContent="Voice: verified ✓";badge.style.borderColor="#22c55e";}else{badge.textContent="Voice: not verified";}renderArtistTracks(mine);}renderDiscover();const subBox=document.getElementById("sub-box");if(state.user&&state.user.subscribed){subBox.innerHTML=`<span class="badge ok">Subscribed · $0.50/mo</span>`;}else{subBox.innerHTML=`<span>Listener plan: <strong>$0.50/mo</strong></span><button class="btn primary" id="btn-subscribe">Subscribe</button>`;document.getElementById("btn-subscribe")?.addEventListener("click",subscribe);}}
function renderArtistTracks(mine){const box=document.getElementById("artist-tracks");if(!mine.length){box.className="track-list empty-state";box.textContent="No tracks yet. Upload your first AI track after voice verification.";return;}box.className="track-list";box.innerHTML=mine.map(t=>`<div class="track-row"><div class="meta"><strong>${escapeHtml(t.title)}</strong><span>${t.type} · ${t.streams||0} streams · $${(t.earnings||0).toFixed(2)}</span></div><span class="badge ${t.matchStatus==="passed"?"ok":t.matchStatus==="failed"?"bad":"wait"}">${t.matchStatus==="passed"?"Earning":t.matchStatus==="failed"?"Blocked":"Pending"}</span></div>`).join("");}
function renderDiscover(){const box=document.getElementById("discover-list");const publicTracks=state.tracks.filter(t=>t.matchStatus==="passed");if(!publicTracks.length){box.className="track-list empty-state";box.textContent="No public tracks yet. Be the first verified artist.";return;}box.className="track-list";box.innerHTML=publicTracks.map(t=>`<div class="track-row"><div class="meta"><strong>${escapeHtml(t.title)}</strong><span>by ${escapeHtml(t.artistName)} · ${t.type} · ${t.streams||0} streams</span></div><button class="btn primary" data-stream="${t.id}">Play / Stream</button></div>`).join("");box.querySelectorAll("[data-stream]").forEach(btn=>{btn.addEventListener("click",()=>streamTrack(btn.getAttribute("data-stream")));});}
function escapeHtml(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}
document.getElementById("auth-form").addEventListener("submit",e=>{e.preventDefault();const name=document.getElementById("auth-name").value.trim();const email=document.getElementById("auth-email").value.trim();const role=document.getElementById("auth-role").value;state.user={id:uid(),name,email,role,voiceVerified:false,voiceSampleMeta:null,subscribed:false,createdAt:Date.now()};save();toast(`Welcome, ${name}`);if(role==="artist")showView("voice");else showView("discover");});
document.getElementById("btn-logout").addEventListener("click",()=>{state.user=null;save();showView("home");toast("Signed out");});
async function startCapture(){try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});state.chunks=[];state.mediaRecorder=new MediaRecorder(stream);state.mediaRecorder.ondataavailable=e=>{if(e.data.size>0)state.chunks.push(e.data);};state.mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());state.voiceBlob=new Blob(state.chunks,{type:"audio/webm"});const url=URL.createObjectURL(state.voiceBlob);const audio=document.getElementById("voice-playback");audio.src=url;audio.classList.remove("hidden");document.getElementById("btn-save-voice").classList.remove("hidden");document.getElementById("voice-status").textContent="Capture complete. Listen back, then save fingerprint.";document.getElementById("wave").classList.remove("live");};state.mediaRecorder.start();document.getElementById("btn-rec-start").disabled=true;document.getElementById("btn-rec-stop").disabled=false;document.getElementById("voice-status").textContent="Recording… speak the prompt clearly.";document.getElementById("wave").classList.add("live");}catch(err){toast("Mic permission needed for live voice capture");document.getElementById("voice-status").textContent="Microphone blocked. Allow mic access and try again.";}}
function stopCapture(){if(state.mediaRecorder&&state.mediaRecorder.state!=="inactive")state.mediaRecorder.stop();document.getElementById("btn-rec-start").disabled=false;document.getElementById("btn-rec-stop").disabled=true;}
document.getElementById("btn-rec-start").addEventListener("click",startCapture);
document.getElementById("btn-rec-stop").addEventListener("click",stopCapture);
document.getElementById("btn-save-voice").addEventListener("click",()=>{if(!state.user||!state.voiceBlob)return;state.user.voiceVerified=true;state.user.voiceSampleMeta={bytes:state.voiceBlob.size,type:state.voiceBlob.type,capturedAt:Date.now(),print:hashNum(state.user.id+":"+state.voiceBlob.size)};save();toast("Voice fingerprint saved. You can upload AI tracks now.");showView("artist");});
function hashNum(str){let h=0;for(let i=0;i<str.length;i++)h=(Math.imul(31,h)+str.charCodeAt(i))|0;return Math.abs(h);}
document.getElementById("upload-form").addEventListener("submit",async e=>{e.preventDefault();const result=document.getElementById("match-result");result.classList.remove("hidden","ok","bad");if(!state.user||state.user.role!=="artist"){toast("Artist account required");return;}if(!state.user.voiceVerified){result.classList.add("bad");result.textContent="Voice not verified. Complete live capture first.";showView("voice");return;}const title=document.getElementById("track-title").value.trim();const type=document.getElementById("track-type").value;const file=document.getElementById("track-file").files[0];if(!file)return;result.textContent="Running voice-match gate…";await sleep(900);const matchScore=0.82+(hashNum(title+file.name)%15)/100;const passed=matchScore>=0.75;const track={id:uid(),artistId:state.user.id,artistName:state.user.name,title,type,fileName:file.name,fileSize:file.size,matchStatus:passed?"passed":"failed",matchScore:Number(matchScore.toFixed(3)),streams:0,earnings:0,createdAt:Date.now()};state.tracks.unshift(track);save();if(passed){result.classList.add("ok");result.textContent=`Match score ${track.matchScore} — PASSED. Track is live and can earn from streams.`;toast("Published · earning enabled");}else{result.classList.add("bad");result.textContent=`Match score ${track.matchScore} — FAILED. Voice does not match your verified fingerprint. Not eligible to earn.`;toast("Blocked · voice mismatch");}e.target.reset();refreshUI();});
function subscribe(){if(!state.user){showView("auth");document.getElementById("auth-role").value="listener";toast("Create a listener account first");return;}state.user.subscribed=true;save();toast("Subscribed · $0.50/mo (demo)");refreshUI();}
function streamTrack(id){if(!state.user){showView("auth");toast("Sign in to stream");return;}if(state.user.role==="listener"&&!state.user.subscribed){toast("Subscribe $0.50/mo to stream");return;}const t=state.tracks.find(x=>x.id===id);if(!t||t.matchStatus!=="passed")return;t.streams=(t.streams||0)+1;t.earnings=Number(((t.earnings||0)+0.003).toFixed(4));save();toast(`Streaming “${t.title}” · artist +$0.003`);refreshUI();}
function sleep(ms){return new Promise(r=>setTimeout(r,ms));}
document.querySelectorAll("[data-view]").forEach(el=>{el.addEventListener("click",e=>{e.preventDefault();const v=el.getAttribute("data-view");if(v)showView(v);});});
load();refreshUI();showView("home");
